### ISSUE TITLE
Picking number of regular feature fields and init_as_id for equivariant nets

### ISSUE THREAD

**Issue by belizgunel** [fsherry/equivariant_image_recon#1]
Hi,

Great work, really enjoyed reading it, and thanks for open-sourcing your implementation! I have few questions regarding the implementation of equivariant proximal blocks. Thanks very much in advance.

(1) How did you go about picking the number of regular feature fields as 16 while defining the default feature type? (https://github.com/fsherry/equivariant_image_recon/blob/8733fafa006089a31c468599745f9b127204bdb3/equivariant_ip/proximal_blocks/primal_equivariant.py#L6) And, what is the intuition around what that multiplicity of 16 represents? Input and output feature types are fairly intuitive as we know the number of input channels, and n_memory.

(2) Did you use _set_equal_to_identity function while initializing the equivariant proximal blocks? If so, why was that necessary?

Thanks a lot again!
Beliz

**Comment by fsherry** [comment]
Hi Beliz,

Thank you for your interest in this work and for taking a detailed look at the code.

Regarding your first question, it is good to keep in mind what it means that a vector transforms according to the regular representation of a (finite) group: we identify each coordinate of the vector with an element of the group and the group acts on it by permuting the coordinates. Hence, each such vector has dimensionality equal to the order of the group, and the total width of the network is the multiplicity (16 in the code you linked) times the order of the group (6 in the code you linked). In fact, in our experiments in the paper we used a multiplicity of 24 and a group of order 4, but the same total width (96) is kept the same. This choice was made to ensure that the comparison with the "ordinary" networks is fair: in the background, the equivariant convolutions are performed using ordinary 2d convolutions with constrained kernels, so the "ordinary" network with total width 96 is capable of encoding the "equivariant" network too. A final question might remain regarding the choice of this total width. This is somewhat arbitrary; we found that this number is large enough to give good reconstructions and not cause any memory headaches when training, but there is no particular reason to believe this is the only number that could work.

As for the second question, in the end we did not initialise the proximal blocks as the identity. This was something we initially toyed with a bit because using the standard initialisations for the convolutional filters in the proximal blocks resulted in the proximal blocks having an expansive action on its inputs. Unfortunately, initialising the proximal blocks as the identity (at least in the way that is shown in the code) does not work well since large parts of the network remain dead (zero weights and no involvement in the forward pass so zero gradients). Instead, we ended up with something that can be seen as a compromise between the two ideas: in the formula below, K<sub>lift,i</sub> and K<sub>project,i</sub> were initialised with a standard initialisation for convolutional filters, while K<sub>intermediate,i</sub> was initialised to be zero.

<img width="493" alt="Screenshot 2021-08-09 at 12 38 40" src="https://user-images.githubusercontent.com/12610714/128700542-14957f7e-b984-40f9-8a17-4cce4ca73011.png">

I hope this helps clear some things up.

Ferdia

**Comment by belizgunel** [comment]
Thanks a lot for your thorough explanation, Ferdia -- very much appreciate it. It does clear things up. Just to make sure I understood you correctly about initialization, first_part and final_part in this code was initialized with standard initialization for convolutional filters as they correspond to lift and project operations, meanwhile middle_part --corresponding to K_intermediate operation -- was initialized to zero? https://github.com/fsherry/equivariant_image_recon/blob/8733fafa006089a31c468599745f9b127204bdb3/equivariant_ip/proximal_blocks/primal_equivariant.py#L65 Assuming that's what you meant, this initialization change gave us a large performance boost while trying to replicate your results.

**Comment by fsherry** [comment]
Hi Beliz, that's right. To match the code that you reference above to what we did in the paper, n_res_blocks should equal 1, in which case middle_part will just be (id + phi ∘ K<sub>intermediate,i</sub>). By initialising K<sub>intermediate,i</sub> to be zero, middle_part will equal the identity at initialisation. The following two snippets show exactly how we did this in the experiments:
https://github.com/fsherry/equivariant_image_recon/blob/8733fafa006089a31c468599745f9b127204bdb3/scripts/equivariant_brain_mri.py#L92-L97

https://github.com/fsherry/equivariant_image_recon/blob/8733fafa006089a31c468599745f9b127204bdb3/scripts/equivariant_brain_mri.py#L113-L115
